artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/quamrl-hoda/dataset/raw/refs/heads/main/gemstone.zip
  local_data_file: artifacts/data_ingestion/gemstone.zip
  unzip_dir: artifacts/data_ingestion
  # raw_data_path: artifacts/raw.csv
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/gemstone.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/train.csv
  test_data_path: artifacts/test.csv
  preprocessor_obj_file_path: artifacts/data_transformation/preprocessor.pkl



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json





